name: Test usage as an Action

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: styfle/cancel-workflow-action@0.9.1
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cache/pip
        key: ubuntu-latest

    - name: Upgrade pip; install requirements
      run: |
        python -m pip install --upgrade pip pytest-cov \
          click Jinja2 requests

    - name: Run pytest to generate a coverage file; copy; then run all tests
      run: pytest --color=yes . -k nothing --cov .

    - name: Invoke the CLI to annotate the PR
      uses: khaeru/coverage-gh@main
